name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-2019, vs: "Visual Studio 2019" }
          - { os: windows-2022, vs: "Visual Studio 2019" }
        build: [Debug, Release]
        platform: [Win32, x64]

    name: "${{matrix.config.vs}}:${{matrix.platform}}:${{matrix.build}}"

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1.1.1

    - name: 'Build'
      run: |
        # Build the project, without unittests
        dub build
        # Build and run tests
        dub test -b unittest-cov
